export const READ_ALL = 'ACCOUNTS_USERS_READ_ALL';
export const READ = 'ACCOUNTS_USERS_READ';
export const UPDATE = 'ACCOUNTS_USERS_UPDATE';
export const DELETE = 'ACCOUNTS_USERS_DELETE';
export const CREATE = 'ACCOUNTS_USERS_CREATE';
