export const READ = 'NOTIFICATIONS_READ';
export const DELETE_ALL_NOTIFICATIONS = 'NOTIFICATIONS_DELETE_ALL_NOTIFICATIONS';
export const DELETE_NOTIFICATIONS = 'NOTIFICATIONS_DELETE_NOTIFICATIONS';
export const DELETE_NOTIFICATION = 'NOTIFICATIONS_DELETE_NOTIFICATION';
