export const READ_CLIENT_CREDENTIALS = 'INTEGRATIONS_READ_CLIENT_CREDENTIALS';
export const READ_CREDENTIAL = 'INTEGRATIONS_READ_CREDENTIAL';
export const READ = 'INTEGRATIONS_READ';
export const READ_AUTHORIZATIONS = 'INTEGRATIONS_READ_AUTHORIZATIONS';
export const READ_ALL = 'INTEGRATIONS_READ_ALL_ACTIVE';
export const CREATE_CODE = 'INTEGRATIONS_CREATE_CODE';
export const DISABLE = 'INTEGRATIONS_DISABLE';
